#!/bin/bash
#
# This script is run indirectly via tela_run_quote.sh since we need to
# re-use the matching data generated by a previous call to 'tela match'.
#

TELARC="tela_run_quote.telarc"

# Loop over all attributes found in TELARC and compare actual environment
# variable values with expected values
NUM_MISMATCH=0
IFS="#"
while read -r key exp ; do
	[[ "$key" =~ ^\  ]] || continue

	IFS=$' \t:' read key rest <<<"$key"

	# Extract attribute name and expected value
	key="${key%%:*}"
	exp="${exp##*#}"
	exp="${exp:1}"

	# Get actual value in quoted form
	name="TELA_SYSTEM_DUMMY_a_${key^^}"
	eval act="\${$name@Q}"

	# Compare
	if [[ "$act" != "$exp" ]] ; then
		echo -n "[fail] "
		(( NUM_MISMATCH++ ))
	else
		echo -n "[pass] "
	fi
	echo "$name expected=[$exp] actual=[$act]"
done < "$TELARC"

if [[ "$NUM_MISMATCH" -eq 0 ]] ; then
	echo "SUCCESS"
else
	echo "NUM_MISMATCH=$NUM_MISMATCH"
fi

exit 0
