include ../../../tela.mak

# Ensure deterministic results independent of test system's telarc
export TELA_RC := /dev/null

TESTS := simple_noplan.sh simple_nosub.sh simple_sub.sh multi_sub.sh
TESTS += mismatch.sh
